export const ROUTES = {
  LOGIN: '/login',
  REGISTER_TENANT: '/register-tenant',
  DASHBOARD: '/dashboard',
  PRODUCTS: '/products',
  SUPPLIERS: '/suppliers',
  STOCK_INS: '/stock-ins',
  STOCK_OUTS: '/stock-outs',
  INVENTORY: '/inventory',
  USERS: '/users',
  TIKTOK_SHOPS: '/settings/tiktok-shops',
  PRODUCT_MAPPINGS: '/product-mappings',
  TIKTOK_ORDERS: '/tiktok-orders',
  TIKTOK_RETURNS: '/tiktok-returns',
  TIKTOK_FINANCE: '/tiktok-finance',
  PROFILE: '/profile',
} as const
